In [1]:
import numpy as np

print(f"numpy version: {np.__version__}")

numpy version: 1.24.3


In [7]:
x = np.zeros(9)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
def get_action_index(action):
    x, y = action
    action_index = x * 3 + y
    return action_index

In [13]:
print(get_action_index((0,0)))
print(get_action_index((0,1)))
print(get_action_index((0,2)))
print(get_action_index((1,0)))
print(get_action_index((1,1)))
print(get_action_index((1,2)))
print(get_action_index((2,0)))
print(get_action_index((2,1)))
print(get_action_index((2,2)))

0
1
2
3
4
5
6
7
8


In [15]:
def get_state_key(state):
    return ''.join([f"{int(item)}" for item in state])

In [16]:
get_state_key([1.0, 0.0, 1.0, 0.0])

'1010'

In [1]:
import numpy as np

x = [1.0, 2.0, 3.0]
y = [1.5, 2.5, 3.5]

concatenated = np.concatenate((x, y), axis=None)
print(concatenated)

[1.  2.  3.  1.5 2.5 3.5]


In [2]:
features = np.zeros(9)
print(features)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
def get_action_features(action):
    x, y = action
    action_index = x * 3 + y
    action_features = np.zeros(9)
    action_features[action_index] = 1.0
    return action_features

action = (1,1)
get_action_features(action)

array([0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [3]:
l = [1, 5]
tup = (2,3)

l.append(tup)

print(l)

[1, 5, (2, 3)]


In [4]:
len(l)

3

In [5]:
import pandas as pd
print(f"pandas: {pd.__version__}")


pandas: 2.1.4


In [7]:
df = pd.DataFrame(data = [(1, "one"), (2, "two"), (3, "three"), (4, "four")], columns=['digits', 'strings'])
df

,digits,strings
0,1,one
1,2,two
2,3,three
3,4,four


In [11]:
for row in df.itertuples():
    print(f"{row.digits} {row.strings}")

1 one
2 two
3 three
4 four


In [15]:
data = [(1, "one"), (2, "two"), (3, "three"), (4, "four")]

length = len(data)
for i in reversed(range(length)):
    data_1, data_2 = data[i]
    if i == length - 1:
        v = data_1
    else:
        v = 0.3
    data[i] = (v, data_2)

data

[(0.3, 'one'), (0.3, 'two'), (0.3, 'three'), (4, 'four')]