In [19]:
import tensorflow as tf
import keras
import numpy
import copy

print(f"tensorflow: {tf.__version__} keras: {keras.__version__} numpy: {numpy.__version__}")

tensorflow: 2.16.1 keras: 3.3.3 numpy: 1.26.4


In [20]:
model = keras.models.Sequential(
    [
        keras.Input(shape=(2, )),
        keras.layers.Dense(2, activation="linear"),
    ]
)

model_snapshot = copy.deepcopy(model)

In [23]:

x = model(input_1)
print(f"model: {x}")

x = model_snapshot(input_1)
print(f"snapshot: {x}")


model: [[ 0.3210377 -1.9471922]]
snapshot: [[ 0.3210377 -1.9471922]]


In [27]:
input_1 = tf.Variable([[1.0, 1.0]])
expected_y_1 = tf.Variable([[0.3210377, 0.5]])

print(f"input: {input_1}")
print(f"expected_output: {expected_y_1}")

with tf.GradientTape(persistent=True) as tape:
    output_1 = model(input_1)
    loss = tf.abs(expected_y_1 - output_1)

gradients = tape.gradient(loss, model.trainable_weights)

print(f"output: {output_1}")
print(f"loss: {loss}")
print(f"gradients: {gradients}")

for layer in model.layers:
    print(f"layer {layer.name} weights: {layer.get_weights()}")

input: <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 1.]], dtype=float32)>
expected_output: <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0.3210377, 0.5      ]], dtype=float32)>
output: [[ 0.3210377 -1.9471922]]
loss: [[0.        2.4471922]]
gradients: [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0., -1.],
       [-0., -1.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0., -1.], dtype=float32)>]
layer dense_1 weights: [array([[-0.29516667, -1.0772337 ],
       [ 0.6162044 , -0.86995846]], dtype=float32), array([0., 0.], dtype=float32)]


In [36]:
optimizer = keras.optimizers.SGD(learning_rate=0.1)
optimizer.apply_gradients(zip(gradients, model.trainable_weights))

for layer in model.layers:
    print(f"layer {layer.name} weights: {layer.get_weights()}")

x = model(input_1)
print(f"model output: {x}")

layer dense_1 weights: [array([[-0.29516667, -0.47723356],
       [ 0.6162044 , -0.2699584 ]], dtype=float32), array([0. , 0.6], dtype=float32)]
model output: [[ 0.3210377  -0.14719194]]
