In [36]:
import random
import tensorflow as tf
import keras
import numpy as np

from keras import layers
from keras import models
from keras import initializers

print(f"tensorflow version: {tf.__version__}, keras version: {keras.__version__}")


tensorflow version: 2.17.0, keras version: 3.4.1


In [120]:
nn_model = models.Sequential([
            layers.Input(shape=(2,)),
            layers.Dense(2, activation=keras.activations.leaky_relu,
                         kernel_initializer=initializers.RandomNormal(stddev=0.05),
                         bias_initializer=initializers.RandomNormal(stddev=0.05)),
            layers.Dense(2, activation=keras.activations.linear,
                         kernel_initializer=initializers.RandomNormal(stddev=0.05),
                         bias_initializer=initializers.RandomNormal(stddev=0.05))
        ])

In [121]:
input_state_1 = tf.convert_to_tensor([[1.0, 0.0]])

output_1 = nn_model(input_state_1)

print(f"output: {output_1}")

expected_output_1 = tf.Variable(initial_value=output_1, trainable=False)

temp = expected_output_1.numpy()
temp[0][1] = 0.75

expected_output_1.assign(temp)

print(f"expected output: {expected_output_1.numpy()}")



output: [[-0.09159092  0.02679806]]
expected output: [[-0.09159092  0.75      ]]


In [137]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

with tf.GradientTape() as tape:
    predicted_values = nn_model(input_state_1, training=True)
    diff = tf.slice(tf.subtract(expected_output_1, predicted_values), [0,1], [-1,1])
    loss = tf.abs(diff)
    print(f"loss: {loss}")

gradients = tape.gradient(loss, nn_model.trainable_weights)

print(f"gradients: {gradients}")

optimizer.apply_gradients(zip(gradients, nn_model.trainable_variables))

#for i, gradient in enumerate(gradients):
#    nn_model.trainable_weights[i].assign_sub(learning_rate * gradient)


loss: [[0.69312716]]
gradients: [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00053632,  0.01700617],
       [ 0.        ,  0.        ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.00053632,  0.01700617], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.        , -0.03645661],
       [ 0.        , -0.02237066]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0., -1.], dtype=float32)>]


<KerasVariable shape=(), dtype=int64, path=SGD/iteration>

In [138]:
output_1 = nn_model(input_state_1)
print(f"output: {output_1}")
print(f"expected output: {expected_output_1.numpy()}")


output: [[-0.09156142  0.06689686]]
expected output: [[-0.09159092  0.75      ]]


In [87]:
print(f"gradients: {gradients}")

gradients: [<tf.Tensor: shape=(18, 18), dtype=float32, numpy=
array([[-4.4202805e-04,  3.9368868e-04, -1.5006438e-04,  2.5607549e-04,
         9.1431444e-05, -3.8958539e-04, -1.6630992e-03, -9.5366733e-05,
        -1.0802265e-05,  1.0467684e-04, -1.0860930e-03,  1.8808093e-04,
         2.6234431e-04, -1.7854607e-03, -1.2198813e-06,  2.6881360e-04,
         2.0657192e-04,  1.2484430e-04],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [-4.4202805e-04,  3.9368868e-04, -1.5006438e-04,  2.5607549e-04,
         9.1431444e-05, -3.8958539e-04, -1.6630992e-03, -9.5366733e-05,
        -1.0802265e-05,  1.0467684e-04, -1.0860930e-03,  1.8808093e-04,
         2.6234431e-04, -1.7854607e-03, -1.2198813e-06,  2.68813