In [19]:
import tensorflow as tf
import keras
import numpy
import copy

print(f"tensorflow: {tf.__version__} keras: {keras.__version__} numpy: {numpy.__version__}")

tensorflow: 2.16.1 keras: 3.3.3 numpy: 1.26.4


In [40]:
model = keras.models.Sequential(
    [
        keras.Input(shape=(2, )),
        keras.layers.Dense(2, activation="sigmoid"),
    ]
)

model_snapshot = copy.deepcopy(model)

In [41]:

x = model(input_1)
print(f"model: {x}")

x = model_snapshot(input_1)
print(f"snapshot: {x}")


model: [[0.17137074 0.61846256]]
snapshot: [[0.17137074 0.61846256]]


In [43]:
input_1 = tf.Variable([[1.0, 1.0]])
expected_y_1 = tf.Variable([[0.17137074, -0.5]])

print(f"input: {input_1}")
print(f"expected_output: {expected_y_1}")

with tf.GradientTape(persistent=True) as tape:
    output_1 = model(input_1)
    loss = tf.abs(expected_y_1 - output_1)

gradients = tape.gradient(loss, model.trainable_weights)

print(f"output: {output_1}")
print(f"loss: {loss}")
print(f"gradients: {gradients}")

for layer in model.layers:
    print(f"layer {layer.name} weights: {layer.get_weights()}")

input: <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 1.]], dtype=float32)>
expected_output: <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[ 0.17137074, -0.5       ]], dtype=float32)>
output: [[0.17137074 0.61846256]]
loss: [[0.        1.1184626]]
gradients: [<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.        ,  0.23596662],
       [-0.        ,  0.23596662]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.        ,  0.23596662], dtype=float32)>]
layer dense_2 weights: [array([[-0.45409453,  0.51101017],
       [-1.121849  , -0.02798259]], dtype=float32), array([0., 0.], dtype=float32)]


In [44]:
optimizer = keras.optimizers.SGD(learning_rate=0.1)
optimizer.apply_gradients(zip(gradients, model.trainable_weights))

for layer in model.layers:
    print(f"layer {layer.name} weights: {layer.get_weights()}")


layer dense_2 weights: [array([[-0.45409453,  0.4874135 ],
       [-1.121849  , -0.05157926]], dtype=float32), array([ 0.        , -0.02359666], dtype=float32)]


In [45]:
x = model(input_1)
print(f"model output: {x}")

x = model_snapshot(input_1)
print(f"model snapshot output: {x}")

model output: [[0.17137074 0.60162425]]
model snapshot output: [[0.17137074 0.61846256]]


In [2]:

x = [("test", 1), ("second", 2), ("third", 3)]
found = [item for item in x if item[0] == "second"]

print(found[0])


('second', 2)
