In [18]:
import numpy as np

print(f"numpy version: {np.__version__}")

s = np.random.binomial(1, 0.5)

if (s):
    print("yes")
else:
    print("no")

if np.random.binomial(1, 0.5):
    print("yes (2)")
else:
    print("no (2)")

numpy version: 1.24.3
no
yes (2)


In [21]:
import moviepy

print(f"moviepy version: {moviepy.__version__}")

moviepy version: 1.0.3


In [22]:
import tensorflow as tf

print(f"tensorflow version: {tf.__version__}")

tensorflow version: 2.16.1


In [36]:
states = tf.convert_to_tensor([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]], dtype=tf.float32)
actions = tf.convert_to_tensor([1, 0, 1], dtype=tf.int64)
rewards = tf.convert_to_tensor([0.5, 0.4, 0.6], dtype=tf.float32)
next_states = tf.convert_to_tensor([[1.5, 2.5], [2.5, 3.5], [3.5, 4.5]], dtype=tf.float32)
is_done = tf.convert_to_tensor([0, 0, 1], dtype=tf.uint8)


In [49]:
predicted_qvalues = tf.convert_to_tensor([[0.75, 0.1], [0.25, 0.5], [0.4, 0.6]], dtype=tf.float32)
print(f"predicted_qvalues:\n {predicted_qvalues}")

one_hot = tf.one_hot(actions, 2)
print(f"one_hot:\n {one_hot}")

predicted_qvalues_for_actions = tf.reduce_sum(predicted_qvalues * one_hot, axis=-1)
print(f"predicted_qvalues_for_actions:\n {predicted_qvalues_for_actions}")

predicted_next_qvalues = tf.convert_to_tensor([[0.45, 0.25], [0.33, 0.44], [0.28, 0.74]], dtype=tf.float32)
print(f"predicted_next_qvalues:\n {predicted_next_qvalues}")

next_state_values = tf.reduce_max(predicted_next_qvalues, axis=-1)
print(f"next_state_values:\n {next_state_values}")

predicted_qvalues:
 [[0.75 0.1 ]
 [0.25 0.5 ]
 [0.4  0.6 ]]
one_hot:
 [[0. 1.]
 [1. 0.]
 [0. 1.]]
predicted_qvalues_for_actions:
 [0.1  0.25 0.6 ]
predicted_next_qvalues:
 [[0.45 0.25]
 [0.33 0.44]
 [0.28 0.74]]
next_state_values:
 [0.45 0.44 0.74]
